import i18n from 'i18next';
import LanguageDetector from "i18next-browser-languagedetector";
import {initReactI18next} from "react-i18next";

i18n.use(LanguageDetector).use(initReactI18next).init({
    // debug: true,
    lng: localStorage.getItem('language') || 'uz', // LocalStorage'dan tildan foydalanadi yoki default tilni o'rnatadi
    fallbackLng: 'uz',
    interpolation: {
        escapeValue: false,
    },
    resources: {
        uz: {
            translation:
                {
                    success: 'Muvoffaqiyatli',
                    error: 'Xatolik!',
                    telefon: 'Telefon',
                    getCode: 'Kod olish',
                    errorPhone: 'Telefon raqam 12 belgidan iborat',
                    errorCode: 'Kod 6 belgidan iborat',
                    code: 'Kod',
                    submit: 'Tasdiqlash',
                    yil: 'Yil',
                    'Kriditga hisoblash':'Kriditga hisoblash',
                    Parametrlar: 'Parametrlar',
                    'Chiqarilgan yili':'Chiqarilgan yili',
                    'Dvigatel hajmi':'Dvigatel hajmi',
                    'Yurgan masofa':'Yurgan masofa',
                    'Uzatuv qutisi':'Uzatuv qutisi',
                    'Kuzov turi':'Kuzov turi',
                    'Tortuvchi tomon':'Tortuvchi tomon',
                    "Yoqilg'i turi":"Yoqilg'i turi",
                    "Bo'yoq holati":"Bo'yoq holati",
                    'Kridetga':'Kridetga',
                    'Iloji bor':'Iloji bor',
                    "Iloji yoq":"Iloji yo'q",
                    "boshqa narx":'Boshqa {{car}} avtomabillari orasida narx darajasi',
                    "Qisqacha ma'lumot":"Qisqacha ma'lumot",
                    "Xaritadagi joylashuvi":"Xaritadagi joylashuvi",
                    "Sotuvchiga qo'ng'iroq qilish":"Sotuvchiga qo'ng'iroq qilish",
                    "Shikoyatingizni kiriting":"Shikoyatingizni kiriting",
                    "Yuborish":"Yuborish",
                    "So'rovingiz bo'yicha 0ta e'lon topildi":"So'rovingiz bo'yicha {{n}}ta e'lon topildi",
                    "KRIDETGA HISOBLASH":"KRIDETGA HISOBLASH",
                    "Kridet muddati":"Kridet muddati",
                    "Oylar soni":"Oylar soni",
                    "Oylik to'lov":"Oylik to'lov",
                    "Birinchi to'lov usd":"Birinchi to'lov {{val}}",
                    "AVTO BARAKA":"AVTO BARAKA",
                    "Tanlanganlar":"Tanlanganlar",
                    "E'lon joylash":"E'lon joylash",
                    "Suxbatlar":"Suxbatlar",
                    "KABINET":"KABINET",
                    "Xabarni kiriting":"Xabarni kiriting",
                    "Xabar yuborildi":"Xabar yuborildi",
                    "Tasdiqlanganlar":"Tasdiqlangan",
                    "Faol emas":"Faol emas",
                    "Blok qilingan":"Blok qilingan",
                    "E'lon mavjud emas":"E'lon mavjud emas",
                    "Narxni o'zgartirish":"Narxni o'zgartirish",
                    "Topga chiqarish":"Topga chiqarish",
                    "O'chirish":"O'chirish",
                    "Yangi narxni kiriting":"Yangi narxni kiriting",
                    "Diqqat":"Diqqat",
                    "E'lon o'chirilgandan kiyin ma'lumotlarni tiklab bo'lmaydi":"E'lon o'chirilgandan kiyin ma'lumotlarni tiklab bo'lmaydi",
                }

        },
        ru: {
            translation: {
                success: 'Успешный',
                error: "Ошибка",
                telefon: 'Телефон',
                getCode: 'Получить код',
                errorPhone: 'Телефонний номер 12 символов',
                errorCode: 'Код 6 символов',
                code: 'Код',
                submit: 'подтвердить',
                yil: 'Год',
                'Kriditga hisoblash':'Кредитный расчет',
                Parametrlar: 'Параметры',
                'Chiqarilgan yili':'Год выпуска',
                'Dvigatel hajmi':'Скорость движения',
                'Yurgan masofa':'Страна производства',
                'Uzatuv qutisi':'Размер узата',
                'Kuzov turi':'Тип кузова',
                'Tortuvchi tomon':'Торговая марка',
                "Yoqilg'i turi":"Не выпущенный",
                "Bo'yoq holati":"Безопасность",
                'Kridetga':'Кредитный расчет',
                'Iloji bor':'Имеется',
                "Iloji yo'q":"Нет",
                "boshqa narx":'Стоимость {{car}} автомобилей на данной модели',
                "Qisqacha ma'lumot":"Краткая информация",
                "Xaritadagi joylashuvi":"Интернет-карта",
                "Sotuvchiga qo'ng'iroq qilish":"Оформление заявки на кредит",
                "Shikoyatingizni kiriting":"Введите свои данные",
                "Yuborish":"Отправить",
                "So'rovingiz bo'yicha 0ta e'lon topildi":"Сообщение отправлено на {{n}} телефон",
                "KRIDETGA HISOBLASH":"КРЕДИТНА�� СЧ��ТНА�� СТОИМОСТ��",
                "Kridet muddati":"Срок кредита",
                "Oylar soni":"Количество пассажиров",
                "Oylik to'lov":"Стоимость перевозки",
                "Birinchi to'lov usd":"Первый платеж в {{val}}",
                "AVTO BARAKA":"АВТО БАРАКА",
                "Tanlanganlar":"Избранные авто",
                "E'lon joylash":"Добавить авто",
                "Suxbatlar":"Сообщения",
                "KABINET":"Личный кабинет",
                "Xabarni kiriting":"Оставить сообщение",
                "Xabar yuborildi":"Оставить сообщение",
                "Tasdiqlanganlar":"Отправленные сообщения",
                "Faol emas":"Не отправлено",
                "Blok qilingan":"Блокировано",
                "E'lon mavjud emas":"Этот объявление не найдено",
                "Narxni o'zgartirish":"Изменить цену",
                "Topga chiqarish":"Удалить объявление",
                "O'chirish":"Удалить",
                "Yangi narxni kiriting":"Введите новую цену",
                "Diqqat":"Предупреждение",
                "E'lon o'chirilgandan kiyin ma'lumotlarni tiklab bo'lmaydi":"Объявление удалено, но данные о нем не удалены",
            }
        }
    }
});